### ISSUE TITLE
pyenv latest install fails, says "Latest version is '  3.8.5'"

### ISSUE THREAD

**Issue by mrgnw** [momo-lab/xxenv-latest#11]
`pyenv latest install` fails, presumably because `pyenv install` output includes spaces

```sh
$ pyenv latest install
Latest version is '  3.8.5'
Usage: pyenv install [-f] [-kvp] <version>
# ... pyenv install output continues
```
same with `pyenv latest install 3.8.5`
### pyenv install output
```sh
$ pyenv install -l | grep 3.8
  3.8.0
  3.8-dev
  3.8.1
  3.8.2
  3.8.3
  3.8.4
  3.8.5
  miniconda-3.8.3
  miniconda3-3.8.3
```
### manual install works
`pyenv virtualenv 3.8.5 projname` works

```
$ pyenv versions                  
* system (set by /Users/myusername/.pyenv/version)
  3.8.5
  3.8.5/envs/projname
  projname
```

### environment
macOS 10.15.6 Catalina
pyenv installed [via homebrew](https://github.com/pyenv/pyenv#homebrew-on-macos)
```sh
$ pyenv -v                  
pyenv 1.2.20
```

**Comment by druchoo** [comment]
@momo-lab @mrgnw, PR #12 submitted to address this issue.

**Comment by momo-lab** [comment]
marged.
