### ISSUE TITLE
Enhance pypy support

### ISSUE THREAD

**Issue by Toilal** [momo-lab/xxenv-latest#2]
Thanks for this plugin.

It works nicely with CPython, but pypy support doesn't solves to latest version.

```
pyenv latest install pypy
Latest version is 'pypy-stm-2.5.1'
```

But it should gives `pypy-5.7.1`

**Comment by Toilal** [comment]
ping @momo-lab

**Comment by momo-lab** [comment]
#3 is merged.
#5 is checking now. plz wait.
